import React from "react";
import { usePathname } from "next/navigation";
import Head from "next/head";
import MainComponent from "./MainComponent";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { database } from "../../../FirebaseConfig";
import { useCollection } from "react-firebase-hooks/firestore";
import { collection, query, orderBy } from "firebase/firestore";
function index() {
  try{
  const router = useRouter();
  const { chat } = router.query;
  const { data: session } = useSession();
  const chatId = chat as string;
  
  const [message] = useCollection(
    session && database &&
      query(
        collection(
          database,
          "users",
          session?.user?.email!,
          "chat",
          chatId,
          "messages"
        ),
        orderBy("creatAt","asc")
      )
  );
       
       

  return (
    <div className="w-full  h-screen m-auto overflow-hidden">
      <Head>
        <title>ChatGPT | OpenAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/topchatgptlogo.png" />
      </Head>
      {chatId ? (
        <MainComponent
          chatId={chatId}          
          message={message}
        />
      ) : (
        <span>loading</span>
      )}
    </div>
  );
}catch(err){
  console.warn(err)
}
}

export default index;
