import React from "react";
import Head from "next/head";
import MainComponent from "./MainComponent";
import SideBar from "../SideBar";
import { useSelector } from "react-redux";
import { OpencloseC } from "../../setting/ActionSlice";
function index() {
  const openclose = useSelector(OpencloseC);
  return (
    <div className="w-full h-screen m-auto">
      <Head>
        <title>ChatGPT | OpenAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/topchatgptlogo.png" />
      </Head>
      <div className="w-full h-screen frc justify-between">
      <div
        className={` w-0 950:min-w-[270px] h-screen z-[100]  ${
          openclose ? " animate-slideleft3 absolute " : "hidden 950:flex"
        }`}
      >
        <SideBar />
      </div>
       <MainComponent />
      </div>
      
    </div>
  );
}

export default index;
