import Head from "next/head";
import { Inter } from "next/font/google";

import HomeScreenLogin from "@/components/HomeScreenLogin";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatGPT | OpenAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/topchatgptlogo.png" />
      </Head>
      <main className="w-full h-screen bg-[#343541] frc justify-center ">
        <HomeScreenLogin />
      </main>
    </>
  );
}
